"""Spike of the recording pruner: snapshot, strace log to Phobos policy, replay denial count.

Throwaway prototype for docs/superpowers/plans/2026-10-05-recording-pruner.md. It is not the
implementation: the plan replaces the parser below with the shared one of PR 162 and the
generalisation with PR 162's generalise module. It exists to show that a recorded interactive
session can be turned into a configuration that phobos-policysystem.sh accepts and under which
the same session runs with no denial.

Subcommands:
  snapshot <file>                         every path that exists now, with its type
  generate --snapshot F --trace T [--trace T2 ...] --out CFG
                                          one configuration from one or more sessions
  denials <trace>                         refused calls inside the Landlock domain of a replay
"""

from __future__ import annotations

import argparse
import dataclasses
import ipaddress
import os
import re
import stat
import struct
import sys
from collections.abc import Iterable, Iterator

# Roots whose entries are granted file by file and never widened to a directory (PR 162, A.6.5).
FINE_ROOTS = ("/etc", "/dev", "/proc", "/sys", "/root", "/home", "/run")

# Names that change from one run to the next, with the smallest directory that holds them under
# every name, and the reason written beside the entry in the configuration.
PER_RUN_NAMES = (
    (re.compile(r"^/proc/(\d+|self|thread-self)(/|$)"), "/proc",
     "per-process files under /proc/<pid>, whose number changes with every run"),
    (re.compile(r"^/dev/pts/\d+$"), "/dev/pts",
     "a pseudo-terminal whose number changes with every run"),
)

# Directories never walked by the snapshot: their entries are generated by the kernel per process.
SNAPSHOT_SKIP = ("/proc", "/sys")

# The sections in the order the configuration lists them.
SECTION_ORDER = ("read", "execute", "write", "create", "delete", "create-ipc",
                 "create-symlink", "restructure")

# The right letters each section grants, as phobos-policy-parse.sh feeds them to the enforcer.
SECTION_LETTERS = {
    "read": "r",
    "execute": "x",
    "write": "w",
    "create": "m",
    "delete": "d",
    "create-ipc": "p",
    "create-symlink": "l",
    "restructure": "mdf",
}

# Sections whose rights are never widened to a containing directory.
WRITE_CLASS = frozenset({"write", "create", "delete", "create-ipc", "create-symlink",
                         "restructure"})

# One strace line: pid, call name, arguments, result, optional errno.
LINE = re.compile(r"^(?P<pid>\d+) +(?P<name>[a-z0-9_]+)\((?P<arguments>.*)\) += "
                  r"(?P<result>-?\d+|\?|0x[0-9a-f]+)(?P<rest>.*)$")
ERRNO = re.compile(r"^ (?P<errno>E[A-Z0-9]+) ")
UNFINISHED = re.compile(r"^(?P<pid>\d+) +(?P<head>.*) <unfinished \.\.\.>$")
RESUMED = re.compile(r"^(?P<pid>\d+) +<\.\.\. (?P<name>[a-z0-9_]+) resumed>(?P<tail>.*)$")

# Address forms strace prints for a socket address.
INET_ADDRESS = re.compile(r'sa_family=AF_INET, sin_port=htons\((\d+)\), '
                          r'sin_addr=inet_addr\("([0-9.]+)"\)')
INET6_ADDRESS = re.compile(r'sa_family=AF_INET6, sin6_port=htons\((\d+)\).*?'
                           r'inet_pton\(AF_INET6, "([0-9a-fA-F:.]+)"')
UNIX_ADDRESS = re.compile(r'sa_family=AF_UNIX, sun_path=(@?)"((?:[^"\\]|\\.)*)"')

# What -yy prints for an INET socket descriptor: 4<TCP:[local->remote]>, or 4<TCP:[local]>.
SOCKET_DECORATION = re.compile(r"<(?:TCP|TCPv6|UDP|UDPv6):\[(?P<ends>.*)\]>$")

# ioctl commands Landlock always allows on a device (the kernel's Landlock documentation).
ALWAYS_ALLOWED_IOCTLS = frozenset({"FIOCLEX", "FIONCLEX", "FIONBIO", "FIOASYNC", "FIFREEZE",
                                   "FITHAW", "FIGETBSZ", "FS_IOC_FIEMAP", "FICLONE",
                                   "FICLONERANGE", "FIDEDUPERANGE"})

# The DNS port, whose answers name the addresses a session later connects to.
DNS_PORT = 53

# The TLS record and handshake types of a ClientHello, which carries the server name.
TLS_HANDSHAKE_RECORD = 0x16
TLS_CLIENT_HELLO = 0x01
TLS_SERVER_NAME_EXTENSION = 0x0000


@dataclasses.dataclass(frozen=True)
class Call:
    """One completed system call of the session."""

    pid: int
    name: str
    arguments: list[str]
    result: str
    decoration: str
    errno: str | None


@dataclasses.dataclass
class Recording:
    """What the sessions needed: path grants with evidence, network rules and fixed refusals."""

    grants: dict[str, set[str]] = dataclasses.field(default_factory=dict)
    evidence: dict[str, set[str]] = dataclasses.field(default_factory=dict)
    connect: dict[str, str] = dataclasses.field(default_factory=dict)
    bind: dict[str, str] = dataclasses.field(default_factory=dict)
    accept: dict[str, str] = dataclasses.field(default_factory=dict)
    fixed: set[str] = dataclasses.field(default_factory=set)
    created: set[str] = dataclasses.field(default_factory=set)
    moves: set[tuple[str, str]] = dataclasses.field(default_factory=set)
    probes: set[str] = dataclasses.field(default_factory=set)
    sessions: int = 0


def split_arguments(text: str) -> list[str]:
    """Splits a strace argument list on top-level commas, outside quotes and brackets."""
    parts = []
    depth = 0
    quoted = False
    escaped = False
    current = []
    for character in text:
        if quoted:
            current.append(character)
            if escaped:
                escaped = False
            elif character == "\\":
                escaped = True
            elif character == '"':
                quoted = False
            continue
        if character == '"':
            quoted = True
        elif character in "([{<":
            depth += 1
        elif character == ">" and current and current[-1] in "-=":
            pass
        elif character in ")]}>":
            depth -= 1
        elif character == "," and depth == 0:
            parts.append("".join(current).strip())
            current = []
            continue
        current.append(character)
    if current:
        parts.append("".join(current).strip())
    return parts


def unescape(quoted: str) -> bytes:
    """Turns a C string as strace prints it, quotes included, into its bytes."""
    body = quoted
    body = body.removesuffix("...")
    if body.startswith('"') and body.endswith('"'):
        body = body[1:-1]
    simple = {"n": 10, "t": 9, "r": 13, "v": 11, "f": 12, '"': 34, "\\": 92}
    out = bytearray()
    index = 0
    while index < len(body):
        character = body[index]
        if character != "\\":
            out += character.encode()
            index += 1
            continue
        following = body[index + 1]
        if following == "x":
            out.append(int(body[index + 2:index + 4], 16))
            index += 4
        elif following in simple:
            out.append(simple[following])
            index += 2
        else:
            digits = re.match(r"[0-7]{1,3}", body[index + 1:]).group(0)
            out.append(int(digits, 8))
            index += 1 + len(digits)
    return bytes(out)


def text_argument(argument: str) -> str:
    """The path a quoted strace argument names."""
    return unescape(argument).decode("utf-8", "surrogateescape")


def descriptor_path(argument: str) -> str | None:
    """The path -yy decorates a descriptor argument with, such as 3</etc/hosts>."""
    match = re.match(r"^(?:-?\d+|AT_FDCWD)<(.*)>$", argument)
    if not match:
        return None
    inner = match.group(1)
    inner = re.sub(r"<(char|block) \d+:\d+>$", "", inner)
    return inner


def parse_trace(lines: Iterable[str]) -> Iterator[Call]:
    """Turns strace -f lines into completed calls, joining unfinished and resumed halves."""
    pending: dict[int, str] = {}
    for raw in lines:
        line = raw.rstrip("\n")
        unfinished = UNFINISHED.match(line)
        if unfinished:
            pending[int(unfinished.group("pid"))] = unfinished.group("head")
            continue
        resumed = RESUMED.match(line)
        if resumed:
            pid = int(resumed.group("pid"))
            head = pending.pop(pid, None)
            if head is None:
                continue
            line = f"{pid} {head}{resumed.group('tail')}"
        match = LINE.match(line)
        if not match:
            continue
        rest = match.group("rest")
        errno = ERRNO.match(rest)
        decoration = rest if rest.startswith("<") else ""
        yield Call(pid=int(match.group("pid")), name=match.group("name"),
                   arguments=split_arguments(match.group("arguments")),
                   result=match.group("result"), decoration=decoration,
                   errno=errno.group("errno") if errno else None)


def joined(directory: str | None, path: str) -> str:
    """An absolute path from a path argument and the directory its descriptor names."""
    if path.startswith("/"):
        return os.path.normpath(path)
    return os.path.normpath(os.path.join(directory or "/", path))


def socket_ends(descriptor: str) -> tuple[tuple[str, int] | None, tuple[str, int] | None]:
    """The local and remote (address, port) of a decorated INET socket descriptor."""
    match = SOCKET_DECORATION.search(descriptor)
    if not match:
        return None, None
    ends = [end_point(text) for text in match.group("ends").split("->", 1)]
    return ends[0], (ends[1] if len(ends) > 1 else None)


def end_point(text: str) -> tuple[str, int] | None:
    """An (address, port) pair from 1.2.3.4:80 or [::1]:80."""
    host, _, port = text.rpartition(":")
    if not port.isdigit():
        return None
    return host.strip("[]"), int(port)


def per_run_directory(path: str) -> tuple[str, str] | None:
    """The stable directory and the reason, when the path is a per-run name."""
    for pattern, directory, reason in PER_RUN_NAMES:
        if pattern.match(path):
            return directory, reason
    return None


def under(path: str, root: str) -> bool:
    """Whether the path is the root or lies beneath it."""
    return path == root or path.startswith(root.rstrip("/") + "/")


class Snapshot:
    """The paths that existed before the session, with their file types."""

    def __init__(self, entries: dict[str, str]):
        self.entries = entries

    @classmethod
    def read(cls, file_path: str) -> Snapshot:
        """Reads a snapshot written by write_snapshot."""
        entries = {}
        with open(file_path, encoding="utf-8", errors="surrogateescape") as handle:
            for line in handle:
                kind, _, path = line.rstrip("\n").partition(" ")
                entries[path] = kind
        return cls(entries)

    def existed(self, path: str) -> bool:
        """Whether the path existed before the session; kernel trees count as existing."""
        if any(under(path, root) for root in SNAPSHOT_SKIP):
            return per_run_directory(path) is None
        return path in self.entries

    def is_directory(self, path: str) -> bool:
        """Whether the path was a directory before the session, or is one now."""
        if self.entries.get(path) == "d":
            return True
        return os.path.isdir(path) and not os.path.islink(path)

    def nearest_existing(self, path: str) -> str:
        """The nearest ancestor of the path, or the path itself, that existed before."""
        candidate = path
        while candidate != "/" and not self.existed(candidate):
            candidate = os.path.dirname(candidate)
        return candidate


def write_snapshot(file_path: str) -> None:
    """Writes every path on this system outside the kernel trees, one 'type path' per line."""
    with open(file_path, "w", encoding="utf-8", errors="surrogateescape") as handle:
        handle.write("d /\n")
        for directory, subdirectories, files in os.walk("/", followlinks=False):
            subdirectories[:] = [name for name in subdirectories
                                 if os.path.join(directory, name) not in SNAPSHOT_SKIP]
            for name in subdirectories:
                path = os.path.join(directory, name)
                kind = "l" if os.path.islink(path) else "d"
                handle.write(f"{kind} {path}\n")
            for name in files:
                path = os.path.join(directory, name)
                handle.write(f"{'l' if os.path.islink(path) else 'f'} {path}\n")


class SessionReader:
    """Walks one session's calls and adds what they needed to a Recording."""

    def __init__(self, recording: Recording, snapshot: Snapshot):
        self.recording = recording
        self.snapshot = snapshot
        self.cwd: dict[int, str] = {}
        self.bound_ports: set[int] = set()
        self.loopback_connects: list[tuple[str, int, str]] = []
        self.external_connects: list[tuple[str, int, str]] = []
        self.names_by_address: dict[str, str] = {}
        self.sni_by_endpoint: dict[tuple[str, int], str] = {}
        self.opened_devices: set[str] = set()
        self.sent_endpoints: set[tuple[str, int]] = set()

    def grant(self, path: str, section: str, why: str) -> None:
        """Records that the path needs the section, and the call that showed it."""
        self.recording.grants.setdefault(path, set()).add(section)
        self.recording.evidence.setdefault(path, set()).add(why)

    def object_grant(self, path: str, section: str, why: str) -> None:
        """Grants a right Landlock checks on the object itself, placed where it can be named."""
        stable = per_run_directory(path)
        if stable:
            self.grant(stable[0], section, f"{why}; {stable[1]}")
            return
        if not self.snapshot.existed(path):
            self.recording.created.add(path)
            self.grant(self.snapshot.nearest_existing(path), section,
                       f"{why} on {path}, which the session created")
            return
        self.grant(path, section, why)

    def parent_grant(self, path: str, section: str, why: str) -> str:
        """Grants a right Landlock checks on the parent directory of the object; answers where."""
        parent = os.path.dirname(path)
        if not self.snapshot.existed(parent):
            target = self.snapshot.nearest_existing(parent)
            self.grant(target, section, f"{why} in {parent}, which the session created")
            return target
        self.grant(parent, section, why)
        return parent

    def read_open(self, call: Call, path_index: int, flags_index: int) -> None:
        """An open that succeeded: read, write and truncate on the object, create on the parent."""
        flags = call.arguments[flags_index] if len(call.arguments) > flags_index else ""
        if call.name == "creat":
            flags = "O_WRONLY|O_CREAT|O_TRUNC"
        if call.name == "openat2":
            flags = call.arguments[2]
        if "O_PATH" in flags:
            return
        resolved = descriptor_path("0" + call.decoration) if call.decoration else None
        directory = descriptor_path(call.arguments[0]) if path_index == 1 else self.cwd.get(call.pid)
        written = joined(directory, text_argument(call.arguments[path_index]))
        target = resolved if resolved and resolved.startswith("/") else written
        if "<char " in call.decoration or "<block " in call.decoration:
            self.opened_devices.add(target)
        why = f"{call.name} {written} {flags}"
        if "O_CREAT" in flags and not self.snapshot.existed(target):
            self.parent_grant(target, "create", why)
        if "O_WRONLY" in flags or "O_RDWR" in flags or "O_TRUNC" in flags:
            self.object_grant(target, "write", why)
        if "O_WRONLY" not in flags:
            self.object_grant(target, "read", why)

    def exec_success(self, call: Call) -> None:
        """An execve that succeeded: execute and read on the binary and its interpreter chain.
        The kernel opens each of them for reading with __FMODE_EXEC, and Landlock's file_open
        hook then asks for READ_FILE as well as EXECUTE."""
        path = joined(self.cwd.get(call.pid), text_argument(call.arguments[0]))
        for link in exec_chain(os.path.realpath(path)):
            self.object_grant(link, "execute", f"execve {path}")
            self.object_grant(link, "read", f"execve {path}")

    def make_in_parent(self, call: Call, directory: str | None, path_argument: str,
                       section: str) -> None:
        """A creation that succeeded: the right on the parent of the new object."""
        path = joined(directory, text_argument(path_argument))
        self.recording.created.add(path)
        self.parent_grant(path, section, f"{call.name} {path}")

    def kind_section(self, path: str) -> str:
        """The creation section a rename or link of this object needs in its new parent."""
        if os.path.islink(path):
            return "create-symlink"
        if os.path.exists(path):
            mode = os.stat(path).st_mode
            if stat.S_ISSOCK(mode) or stat.S_ISFIFO(mode):
                return "create-ipc"
        return "create"

    def move(self, call: Call, old: str, new: str, keeps_source: bool) -> None:
        """A rename or link: delete in the old parent, create in the new, refer across both."""
        section = self.kind_section(new)
        why = f"{call.name} {old} -> {new}"
        self.parent_grant(new, section, why)
        if self.snapshot.existed(new) and not keeps_source:
            self.parent_grant(new, "delete", why)
        if not keeps_source:
            self.parent_grant(old, "delete", why)
        if os.path.dirname(old) != os.path.dirname(new):
            source = self.parent_grant(old, "restructure", why)
            destination = self.parent_grant(new, "restructure", why)
            self.recording.moves.add((source, destination))
        self.recording.created.add(new)

    def socket_address(self, text: str) -> tuple[str, str, int] | None:
        """Family, address and port of a socket address argument."""
        inet = INET_ADDRESS.search(text)
        if inet:
            return "inet", inet.group(2), int(inet.group(1))
        inet6 = INET6_ADDRESS.search(text)
        if inet6:
            address = ipaddress.IPv6Address(inet6.group(2))
            if address.ipv4_mapped:
                return "inet", str(address.ipv4_mapped), int(inet6.group(1))
            return "inet6", str(address), int(inet6.group(1))
        unix = UNIX_ADDRESS.search(text)
        if unix:
            return ("abstract" if unix.group(1) else "unix"), text_argument(f'"{unix.group(2)}"'), 0
        return None

    def transport(self, descriptor: str) -> str:
        """udp or tcp, from the descriptor's decoration."""
        return "udp" if "<UDP" in descriptor else "tcp"

    def network_call(self, call: Call) -> None:
        """connect, sendto, sendmsg, bind, listen and accept that succeeded."""
        descriptor = call.arguments[0] if call.arguments else ""
        if call.name == "bind":
            where = self.socket_address(call.arguments[1])
            if where and where[0] == "unix":
                self.make_in_parent(call, self.cwd.get(call.pid), f'"{where[1]}"', "create-ipc")
            elif where and where[0] in ("inet", "inet6"):
                transport = self.transport(descriptor)
                key = f"allow {where[2]}" + (" udp" if transport == "udp" else "")
                self.recording.bind[key] = f"bind {where[1]}:{where[2]} {transport}"
                self.bound_ports.add(where[2])
            return
        if call.name == "listen":
            local, _ = socket_ends(descriptor)
            if local and local[1] not in self.bound_ports:
                self.recording.bind["allow 0"] = "listen on a socket the session never bound"
            if local:
                self.bound_ports.add(local[1])
            return
        if call.name == "getsockname":
            where = self.socket_address(call.arguments[1])
            if where and where[0] in ("inet", "inet6"):
                self.bound_ports.add(where[2])
            return
        if call.name in ("accept", "accept4"):
            where = self.socket_address(call.arguments[1]) if len(call.arguments) > 1 else None
            if where and where[0] in ("inet", "inet6") and not is_loopback(where[1]):
                self.recording.accept[where[1]] = f"accept from {where[1]}"
            return
        if call.name in ("recvfrom", "recvmsg"):
            self.read_dns_answer(call)
            return
        if call.name in ("write", "sendto") and "<TCP" in descriptor:
            self.read_client_hello(call, descriptor)
        if call.name in ("write", "sendto", "sendmsg", "sendmmsg") and "<UDP" in descriptor:
            _, remote = socket_ends(descriptor)
            if remote:
                self.sent_endpoints.add((unmap(remote[0]), remote[1]))
        where = None
        if call.name == "connect":
            where = self.socket_address(call.arguments[1])
        elif call.name in ("sendto", "sendmsg", "sendmmsg"):
            where = self.socket_address(",".join(call.arguments[1:]))
        if not where:
            return
        transport = self.transport(descriptor)
        if where[0] in ("unix", "abstract"):
            if call.name == "connect":
                self.recording.fixed.add(f"connect to the UNIX socket {where[1]}: the connect "
                                         "guard refuses every UNIX-domain connect")
            return
        if "<NETLINK" in descriptor:
            return
        if call.name != "connect":
            self.sent_endpoints.add((where[1], where[2]))
        if is_loopback(where[1]):
            self.loopback_connects.append((where[1], where[2], transport))
        else:
            self.external_connects.append((where[1], where[2], transport))

    def read_dns_answer(self, call: Call) -> None:
        """Maps every address a DNS answer gives to the name that was asked."""
        text = ",".join(call.arguments)
        if f"htons({DNS_PORT})" not in text and f":{DNS_PORT}]" not in call.arguments[0]:
            return
        buffer_argument = next((argument for argument in call.arguments[1:]
                                if argument.startswith('"')), None)
        if call.name == "recvmsg":
            match = re.search(r'iov_base=("(?:[^"\\]|\\.)*"(?:\.\.\.)?)', text)
            buffer_argument = match.group(1) if match else None
        if not buffer_argument:
            return
        for address, name in dns_answers(unescape(buffer_argument)):
            self.names_by_address[address] = name

    def read_client_hello(self, call: Call, descriptor: str) -> None:
        """Remembers the TLS server name a ClientHello presents on a connected socket."""
        _, remote = socket_ends(descriptor)
        if not remote or not call.arguments[1].startswith('"'):
            return
        name = client_hello_server_name(unescape(call.arguments[1]))
        if name:
            self.sni_by_endpoint[(unmap(remote[0]), remote[1])] = name

    def ioctl_call(self, call: Call) -> None:
        """An ioctl on a device the session opened itself, which no section can grant."""
        path = descriptor_path(call.arguments[0])
        command = call.arguments[1] if len(call.arguments) > 1 else ""
        if path in self.opened_devices and command not in ALWAYS_ALLOWED_IOCTLS:
            self.recording.fixed.add(f"ioctl {command} on {path}, which the session opened: "
                                     "no section grants IOCTL_DEV, so grading refuses it")

    def read(self, calls: Iterable[Call], session_cwd: str) -> None:
        """Adds every successful call of one session to the recording."""
        for call in calls:
            if call.name in ("clone", "clone3", "fork", "vfork") and call.result.isdigit():
                self.cwd[int(call.result)] = self.cwd.get(call.pid, session_cwd)
                continue
            self.cwd.setdefault(call.pid, session_cwd)
            if call.errno and not (call.name == "connect" and call.errno == "EINPROGRESS"):
                continue
            self.dispatch(call)
        self.finish_network()

    def dispatch(self, call: Call) -> None:
        """Hands one successful call to the rule for its kind."""
        name = call.name
        arguments = call.arguments
        cwd = self.cwd.get(call.pid)
        if name in ("chdir",):
            self.cwd[call.pid] = joined(cwd, text_argument(arguments[0]))
        elif name == "fchdir":
            self.cwd[call.pid] = descriptor_path(arguments[0]) or cwd
        elif name in ("open", "creat"):
            self.read_open(call, 0, 1)
        elif name in ("openat", "openat2"):
            self.read_open(call, 1, 2)
        elif name in ("execve", "execveat"):
            self.exec_success(call)
        elif name == "mkdir":
            self.make_in_parent(call, cwd, arguments[0], "create")
        elif name == "mkdirat":
            self.make_in_parent(call, descriptor_path(arguments[0]), arguments[1], "create")
        elif name in ("mknod", "mknodat"):
            self.mknod(call)
        elif name == "symlink":
            self.make_in_parent(call, cwd, arguments[1], "create-symlink")
        elif name == "symlinkat":
            self.make_in_parent(call, descriptor_path(arguments[1]), arguments[2],
                                "create-symlink")
        elif name in ("unlink", "rmdir"):
            self.parent_grant(joined(cwd, text_argument(arguments[0])), "delete", name)
        elif name == "unlinkat":
            path = joined(descriptor_path(arguments[0]), text_argument(arguments[1]))
            self.parent_grant(path, "delete", f"unlinkat {path}")
        elif name in ("rename", "link"):
            self.move(call, joined(cwd, text_argument(arguments[0])),
                      joined(cwd, text_argument(arguments[1])), name == "link")
        elif name in ("renameat", "renameat2", "linkat"):
            self.move(call, joined(descriptor_path(arguments[0]), text_argument(arguments[1])),
                      joined(descriptor_path(arguments[2]), text_argument(arguments[3])),
                      name == "linkat")
        elif name == "truncate":
            self.object_grant(joined(cwd, text_argument(arguments[0])), "write", "truncate")
        elif name == "ioctl":
            self.ioctl_call(call)
        elif name in ("bind", "listen", "connect", "sendto", "sendmsg", "sendmmsg", "accept",
                      "accept4", "recvfrom", "recvmsg", "write", "getsockname"):
            self.network_call(call)

    def mknod(self, call: Call) -> None:
        """mknod of a FIFO or socket needs create-ipc; a device node can never be granted."""
        offset = 1 if call.name == "mknodat" else 0
        directory = descriptor_path(call.arguments[0]) if offset else self.cwd.get(call.pid)
        mode = call.arguments[1 + offset]
        if "S_IFCHR" in mode or "S_IFBLK" in mode:
            self.recording.fixed.add(f"{call.name} of a device node: never granted")
            return
        section = "create-ipc" if ("S_IFIFO" in mode or "S_IFSOCK" in mode) else "create"
        self.make_in_parent(call, directory, call.arguments[offset], section)

    def finish_network(self) -> None:
        """Turns the session's endpoints into [connect] rules."""
        loopback_families = set()
        for address, port, transport in self.loopback_connects:
            if transport == "udp" and (address, port) not in self.sent_endpoints:
                self.recording.probes.add(f"{bracket(address)}:{port}")
                continue
            suffix = " udp" if transport == "udp" else ""
            if port in self.bound_ports:
                family = "v6" if ":" in address else "v4"
                loopback_families.add((family, suffix))
            else:
                self.recording.connect[f"allow {bracket(address)}:{port}{suffix}"] = (
                    f"loopback port {port} that no process of the session bound: a service "
                    "outside the session listened there, and it must exist at grading time too")
        for suffix in ("", " udp"):
            families = {family for family, marker in loopback_families if marker == suffix}
            if families == {"v4", "v6"}:
                self.recording.connect[f"allow localhost{suffix}"] = (
                    "loopback ports the session itself bound, which differ per run")
            elif families == {"v4"}:
                self.recording.connect[f"allow 127.0.0.1:*{suffix}"] = (
                    "loopback ports the session itself bound, which differ per run")
            elif families == {"v6"}:
                self.recording.connect[f"allow [::1]{suffix}"] = (
                    "loopback ports the session itself bound, which differ per run")
        lookups = []
        needs_lookup = False
        for address, port, transport in self.external_connects:
            if transport == "udp" and (address, port) not in self.sent_endpoints:
                self.recording.probes.add(f"{bracket(address)}:{port}")
                continue
            if transport == "udp" and port == DNS_PORT:
                lookups.append(address)
                continue
            needs_lookup = self.external_rule(address, port, transport) or needs_lookup
        for address in sorted(set(lookups)):
            marker = "" if needs_lookup else "# "
            reason = ("an address rule below came from a name the session looked up, and the "
                      "command resolves it itself at grading time" if needs_lookup else
                      "the session's own name lookups; a name rule needs none, since the "
                      "network layer maps its names in /etc/hosts")
            self.recording.connect[f"{marker}allow {bracket(address)}:{DNS_PORT} udp"] = reason

    def external_rule(self, address: str, port: int, transport: str) -> bool:
        """A name rule when TLS named the host, otherwise the address the session reached.
        Answers whether the command still has to look the name up itself at grading time."""
        suffix = " udp" if transport == "udp" else ""
        server_name = self.sni_by_endpoint.get((address, port))
        dns_name = self.names_by_address.get(address)
        if transport == "tcp" and server_name:
            self.recording.connect[f"allow {server_name}:{port}"] = (
                f"TLS host name presented to {address}:{port}; grading needs --resolver, and "
                "the egress broker holds it to that name")
            return False
        note = f"; DNS named it {dns_name}, but without TLS only the address can be held" \
            if dns_name else ""
        self.recording.connect[f"allow {bracket(address)}:{port}{suffix}"] = (
            f"reached at this address{note}")
        return dns_name is not None


def unmap(address: str) -> str:
    """An IPv4-mapped IPv6 address as the IPv4 address it carries, any other unchanged."""
    try:
        parsed = ipaddress.ip_address(address)
    except ValueError:
        return address
    if isinstance(parsed, ipaddress.IPv6Address) and parsed.ipv4_mapped:
        return str(parsed.ipv4_mapped)
    return address


def bracket(address: str) -> str:
    """An IPv6 address in the brackets a [connect] rule writes it in."""
    return f"[{address}]" if ":" in address else address


def is_loopback(address: str) -> bool:
    """Whether the address is a loopback address."""
    try:
        return ipaddress.ip_address(address).is_loopback
    except ValueError:
        return False


def dns_name_at(message: bytes, offset: int) -> tuple[str, int]:
    """Reads a possibly compressed DNS name; returns it and the offset after it."""
    labels = []
    end = None
    jumps = 0
    while offset < len(message) and jumps < 16:
        length = message[offset]
        if length == 0:
            offset += 1
            break
        if length & 0xC0 == 0xC0:
            if end is None:
                end = offset + 2
            offset = ((length & 0x3F) << 8) | message[offset + 1]
            jumps += 1
            continue
        labels.append(message[offset + 1:offset + 1 + length].decode("ascii", "replace"))
        offset += 1 + length
    return ".".join(labels), (end if end is not None else offset)


def dns_answers(message: bytes) -> list[tuple[str, str]]:
    """The A and AAAA addresses of a DNS response, each with the name the query asked."""
    if len(message) < 12:
        return []
    _, flags, questions, answers = struct.unpack("!HHHH", message[:8])
    if not flags & 0x8000 or questions < 1:
        return []
    asked, offset = dns_name_at(message, 12)
    offset += 4
    result = []
    for _ in range(answers):
        _, offset = dns_name_at(message, offset)
        if offset + 10 > len(message):
            break
        record_type, _, _, length = struct.unpack("!HHIH", message[offset:offset + 10])
        data = message[offset + 10:offset + 10 + length]
        offset += 10 + length
        if record_type == 1 and length == 4:
            result.append((str(ipaddress.IPv4Address(data)), asked))
        elif record_type == 28 and length == 16:
            result.append((str(ipaddress.IPv6Address(data)), asked))
    return result


def client_hello_server_name(record: bytes) -> str | None:
    """The server name a TLS ClientHello presents, or None."""
    try:
        if record[0] != TLS_HANDSHAKE_RECORD or record[5] != TLS_CLIENT_HELLO:
            return None
        offset = 5 + 4 + 2 + 32
        offset += 1 + record[offset]
        offset += 2 + int.from_bytes(record[offset:offset + 2], "big")
        offset += 1 + record[offset]
        end = offset + 2 + int.from_bytes(record[offset:offset + 2], "big")
        offset += 2
        while offset + 4 <= end:
            kind = int.from_bytes(record[offset:offset + 2], "big")
            length = int.from_bytes(record[offset + 2:offset + 4], "big")
            if kind == TLS_SERVER_NAME_EXTENSION:
                name_length = int.from_bytes(record[offset + 7:offset + 9], "big")
                return record[offset + 9:offset + 9 + name_length].decode("ascii")
            offset += 4 + length
    except (IndexError, UnicodeDecodeError):
        return None
    return None


def exec_chain(path: str) -> list[str]:
    """The binary and every interpreter the kernel opens to run it (PT_INTERP or #!)."""
    chain = [path]
    try:
        with open(path, "rb") as handle:
            head = handle.read(256)
            if head.startswith(b"#!"):
                interpreter = head[2:].split(b"\n", 1)[0].strip().split()[0].decode()
                return chain + exec_chain(os.path.realpath(interpreter))
            if head.startswith(b"\x7fELF"):
                interpreter = elf_interpreter(handle)
                if interpreter:
                    chain.append(os.path.realpath(interpreter))
    except OSError:
        pass
    return chain


def elf_interpreter(handle) -> str | None:
    """The PT_INTERP path of a 64-bit little-endian ELF file, or None."""
    handle.seek(0)
    header = handle.read(64)
    if header[4] != 2 or header[5] != 1:
        return None
    program_offset = struct.unpack_from("<Q", header, 32)[0]
    entry_size = struct.unpack_from("<H", header, 54)[0]
    entries = struct.unpack_from("<H", header, 56)[0]
    for index in range(entries):
        handle.seek(program_offset + index * entry_size)
        entry = handle.read(entry_size)
        kind = struct.unpack_from("<I", entry, 0)[0]
        if kind == 3:
            offset = struct.unpack_from("<Q", entry, 8)[0]
            size = struct.unpack_from("<Q", entry, 32)[0]
            handle.seek(offset)
            return handle.read(size).rstrip(b"\0").decode()
    return None


def generalise(recording: Recording, snapshot: Snapshot) -> dict[str, set[str]]:
    """Read and execute on a file outside the fine-grained roots widen to its directory."""
    widened: dict[str, set[str]] = {}
    for path, sections in recording.grants.items():
        for section in sections:
            target = path
            outside = not any(under(path, root) for root in FINE_ROOTS)
            if section in ("read", "execute") and outside and not snapshot.is_directory(path):
                target = os.path.dirname(path)
                recording.evidence.setdefault(target, set()).add(f"widened from {path}")
            widened.setdefault(target, set()).add(section)
    return widened


def letters(sections: Iterable[str]) -> set[str]:
    """The right letters a set of sections grants."""
    return {letter for section in sections for letter in SECTION_LETTERS[section]}


def normalise_hierarchy(grants: dict[str, set[str]]) -> dict[str, set[str]]:
    """Raises an entry whose rights are a strict subset of an ancestor's to the ancestor's."""
    result = {path: set(sections) for path, sections in grants.items()}
    for path in sorted(result, key=len):
        for ancestor in sorted(result, key=len):
            if ancestor == path or not under(path, ancestor):
                continue
            mine = letters(result[path])
            theirs = letters(result[ancestor])
            if mine < theirs:
                result[path] |= result[ancestor]
    return result


def refer_source_covers_destination(grants: dict[str, set[str]],
                                    moves: set[tuple[str, str]]) -> dict[str, set[str]]:
    """A file moved across directories may not gain rights in its destination, so the source
    directory is given every section the destination holds (repeated until nothing changes,
    because a directory can be both)."""
    changed = True
    while changed:
        changed = False
        for source, destination in moves:
            missing = grants.get(destination, set()) - grants.get(source, set())
            if missing:
                grants.setdefault(source, set()).update(missing)
                changed = True
    return grants


def render(recording: Recording, grants: dict[str, set[str]]) -> str:
    """The configuration text: a header, the sections, the comments and the refusals."""
    lines = [
        "# Recorded by the Phobos recording pruner (spike), not pruned and not reviewed.",
        f"# Sessions merged: {recording.sessions}. It grants what those sessions exercised and",
        "# nothing else: a code path no session took is denied at grading time.",
        "# Recorded on the instructor's reference program; never record an untrusted submission.",
        "",
    ]
    for section in SECTION_ORDER:
        paths = sorted(path for path, sections in grants.items() if section in sections)
        if not paths:
            continue
        lines.append(f"[{section}]")
        for path in paths:
            stable = per_run_directory(path + "/0")
            note = f"  # {stable[1]}" if stable and stable[0] == path else ""
            lines.append(f"{path}{note}")
        lines.append("")
    if recording.connect:
        lines.append("[connect]")
        for rule, why in sorted(recording.connect.items()):
            lines.append(f"# {why}")
            lines.append(rule)
        lines.append("")
    if recording.bind:
        lines.append("[bind]")
        lines.extend(sorted(recording.bind))
        lines.append("")
    for why in sorted(recording.accept.values()):
        lines.append(f"# [accept] not generated: {why}; choose the public port and write it by hand")
    for probe in sorted(recording.probes):
        lines.append(f"# Not granted: a datagram connect to {probe} that sent nothing, which is how "
                     "getaddrinfo ranks addresses; grading refuses it and the lookup still answers")
    for refusal in sorted(recording.fixed):
        lines.append(f"# Grading will refuse, whatever this file grants: {refusal}")
    return "\n".join(lines).rstrip("\n") + "\n"


def generate(arguments: argparse.Namespace) -> int:
    """Reads every session's trace and writes one configuration."""
    snapshot = Snapshot.read(arguments.snapshot)
    recording = Recording()
    for trace in arguments.trace:
        reader = SessionReader(recording, snapshot)
        with open(trace, encoding="utf-8", errors="surrogateescape") as handle:
            reader.read(parse_trace(handle), arguments.cwd)
        recording.sessions += 1
    grants = normalise_hierarchy(generalise(recording, snapshot))
    grants = normalise_hierarchy(refer_source_covers_destination(grants, recording.moves))
    with open(arguments.out, "w", encoding="utf-8") as handle:
        handle.write(render(recording, grants))
    return 0


def call_key(call: Call) -> tuple[str, str]:
    """What a call asked for, comparable between a recording and a replay: name and object."""
    if call.name in ("openat", "openat2", "mkdirat", "unlinkat", "newfstatat"):
        return call.name, call.arguments[1] if len(call.arguments) > 1 else ""
    if call.name in ("connect", "bind", "sendto"):
        return call.name, re.sub(r"^\d+<[^>]*>", "", ",".join(call.arguments[1:2]))
    return call.name, call.arguments[0] if call.arguments else ""


def restricted_denials(trace_path: str) -> list[Call]:
    """Refusals (EACCES, EPERM, EXDEV) by any process after its own or an ancestor's
    landlock_restrict_self. The layers' helpers are among them; their refusals are told apart
    from the command's by comparison with the recording, not here."""
    restricted: set[int] = set()
    refused = []
    with open(trace_path, encoding="utf-8", errors="surrogateescape") as handle:
        for call in parse_trace(handle):
            if call.name == "landlock_restrict_self" and call.result == "0":
                restricted.add(call.pid)
            elif call.name in ("clone", "clone3", "fork", "vfork") and call.result.isdigit():
                if call.pid in restricted:
                    restricted.add(int(call.result))
            elif call.pid in restricted and call.errno in ("EACCES", "EPERM", "EXDEV"):
                refused.append(call)
    return refused


def succeeded_while_recording(trace_paths: list[str]) -> set[tuple[str, str]]:
    """Every call that succeeded in some recorded session, by call_key."""
    keys = set()
    for trace_path in trace_paths:
        with open(trace_path, encoding="utf-8", errors="surrogateescape") as handle:
            for call in parse_trace(handle):
                if not call.errno or call.errno == "EINPROGRESS":
                    keys.add(call_key(call))
    return keys


def main() -> int:
    """Dispatches the subcommands."""
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    commands = parser.add_subparsers(dest="command", required=True)
    snapshot_command = commands.add_parser("snapshot")
    snapshot_command.add_argument("file")
    generate_command = commands.add_parser("generate")
    generate_command.add_argument("--snapshot", required=True)
    generate_command.add_argument("--trace", action="append", required=True)
    generate_command.add_argument("--cwd", default="/")
    generate_command.add_argument("--out", required=True)
    denials_command = commands.add_parser("denials")
    denials_command.add_argument("--recorded", action="append", required=True)
    denials_command.add_argument("trace")
    arguments = parser.parse_args()
    if arguments.command == "snapshot":
        write_snapshot(arguments.file)
        return 0
    if arguments.command == "generate":
        return generate(arguments)
    recorded = succeeded_while_recording(arguments.recorded)
    refused = restricted_denials(arguments.trace)
    regressions = [call for call in refused if call_key(call) in recorded]
    for call in refused:
        verdict = "DENIED" if call in regressions else "also failed while recording:"
        print(f"{verdict} pid={call.pid} {call.name}({', '.join(call.arguments)[:160]}) {call.errno}")
    print(f"refusals of calls that succeeded while recording: {len(regressions)}")
    print(f"refusals of calls that also failed while recording: {len(refused) - len(regressions)}")
    return 0 if not regressions else 1


if __name__ == "__main__":
    sys.exit(main())
