import { expect, test } from '@playwright/test';

/**
 * Integration tests for the published documentation site.
 *
 * These run against the output of `docusaurus build`, served by `docusaurus serve`, so they
 * check the artefact that is actually deployed. They deliberately cover what the build itself
 * cannot: the build verifies that links resolve, but not that a reader can navigate between
 * the two guides, that the search index is wired to both, or that the site works under the
 * /phobos/ path prefix it is deployed at.
 */

test.describe('landing page', () => {
    test('offers both audiences and reaches each guide', async ({ page }) => {
        await page.goto('./');

        await expect(page.getByRole('heading', { level: 1, name: 'Phobos' })).toBeVisible();

        // Scoped to the main content: the footer links to both guides too, so an unscoped
        // lookup matches twice and fails Playwright's strict mode.
        const cards = page.getByRole('main');
        const user = cards.getByRole('link', { name: /User Documentation/ });
        const contributor = cards.getByRole('link', { name: /Contributor Documentation/ });
        await expect(user).toBeVisible();
        await expect(contributor).toBeVisible();

        await user.click();
        await expect(page).toHaveURL(/\/phobos\/user\//);
        await expect(page.getByRole('heading', { level: 1 })).toContainText('What is Phobos');
    });

    test('the hero states what Phobos is for', async ({ page }) => {
        await page.goto('./');
        await expect(page.getByText(/measures what the program needs/)).toBeVisible();
    });

    const legalPages = [
        { label: 'Imprint', path: 'imprint', heading: 'Imprint' },
        { label: 'Privacy Statement', path: 'privacy', heading: 'Privacy Statement' },
    ];

    for (const { label, path, heading } of legalPages) {
        test(`the footer reaches ${path}`, async ({ page }) => {
            await page.goto('./');
            await page.getByRole('contentinfo').getByRole('link', { name: label, exact: true }).click();
            await expect(page).toHaveURL(new RegExp(`/phobos/${path}`));
            await expect(page.getByRole('heading', { level: 1 })).toContainText(heading);
        });
    }
});

test.describe('the two guides', () => {
    test('the navbar switches between them', async ({ page }) => {
        await page.goto('./user/phobos/what-is-phobos');

        await page.getByRole('navigation').getByRole('link', { name: 'Contributor', exact: true }).click();
        await expect(page).toHaveURL(/\/phobos\/contributor\//);

        await page.getByRole('navigation').getByRole('link', { name: 'User', exact: true }).click();
        await expect(page).toHaveURL(/\/phobos\/user\//);
    });

    test('each guide renders every one of its top-level sections', async ({ page }) => {
        // The sidebars are autogenerated from the directory layout, so a section is present
        // only if its _category_.json and its pages line up. A missing or misplaced category
        // file does not fail the build; the section simply disappears from the sidebar.
        const sidebar = page.getByRole('navigation', { name: 'Docs sidebar' });

        await page.goto('./user/phobos/what-is-phobos');
        for (const section of [
            'Phobos',
            'How to protect anything with Phobos',
            'Policy Cookbook',
            'Policy Reference',
            'Troubleshooting',
        ]) {
            await expect(sidebar.getByText(section, { exact: true }), `user sidebar shows ${section}`).toBeVisible();
        }

        await page.goto('./contributor/how-can-you-contribute');
        for (const section of [
            'How can you contribute',
            'Testing conventions',
            'Life of a sandboxed run',
            'Pruning',
            'Technologies on which Phobos is built',
            'Subsystems',
        ]) {
            await expect(sidebar.getByText(section, { exact: true }), `contributor sidebar shows ${section}`).toBeVisible();
        }
    });

    test('a cross-guide link resolves', async ({ page }) => {
        // The two guides are separate plugin instances, so a link from one to the other is an
        // absolute route rather than a relative file path. That is easy to get wrong and the
        // build only checks that the target exists, not that it is reachable by clicking.
        await page.goto('./user/phobos/what-does-phobos-not-protect-against');
        await page.getByRole('link', { name: /How the discovery phase decides/i }).first().click();
        await expect(page).toHaveURL(/\/phobos\/contributor\/pruning/);
    });
});

test.describe('policy documentation', () => {
    test('every policy reference page marks a section of the example in red', async ({ page }) => {
        // The red marking is produced by a custom Prism magic comment plus a CSS class, and
        // the Docusaurus build cannot confirm that it renders, because it looks at the source
        // rather than at the page.
        const pages = [
            'read', 'execute', 'write', 'create', 'delete', 'create-ipc', 'create-symlink',
            'restructure', 'connect', 'bind', 'accept', 'limits',
        ];

        for (const name of pages) {
            await page.goto(`./user/policy-reference/${name}`);

            const marked = page.locator('.code-block-policy-focus');
            await expect(marked, `${name} must mark part of the example`).not.toHaveCount(0);

            // The magic comments themselves must never be visible to a reader. A page carries
            // more than one code block, so read them all rather than asserting on a locator
            // that matches several and fails Playwright's strict mode.
            const rendered = (await page.locator('pre').allInnerTexts()).join('\n');
            expect(rendered, `${name} must not show the magic comments`).not.toContain('policy-focus-start');
            expect(rendered, `${name} must not show the magic comments`).not.toContain('policy-focus-end');
        }
    });

    test('the marked region is visually distinct from the surrounding code', async ({ page }) => {
        await page.goto('./user/policy-reference/read');
        const marked = page.locator('.code-block-policy-focus').first();
        const background = await marked.evaluate((element) => getComputedStyle(element).backgroundColor);

        // Transparent would mean the class is applied but the stylesheet never reached the page.
        expect(background).not.toBe('rgba(0, 0, 0, 0)');
        expect(background).not.toBe('transparent');
    });
});

test.describe('site behaviour', () => {
    test('search is available and indexes both guides', async ({ page, request }) => {
        await page.goto('./');
        await expect(page.getByRole('textbox', { name: /search/i })).toBeVisible();

        for (const index of ['search-index-user.json', 'search-index-contributor.json']) {
            const response = await request.get(`./${index}`);
            expect(response.status(), `${index} must be published`).toBe(200);
        }
    });

    test('an unknown path renders the 404 page rather than failing', async ({ page }) => {
        const response = await page.goto('./user/this-page-does-not-exist');
        expect(response?.status()).toBe(404);
        await expect(page.getByText(/Page Not Found/i)).toBeVisible();
    });

    // The privacy statement claims this site loads nothing from third parties and sets no
    // cookies. Both are properties a dependency bump could silently break, so assert them
    // rather than trusting that the prose stays true.
    test('the site keeps the promises the privacy statement makes', async ({ page }) => {
        const thirdParty: string[] = [];
        page.on('request', (request) => {
            const { hostname } = new URL(request.url());
            if (hostname !== 'localhost' && hostname !== '127.0.0.1') {
                thirdParty.push(request.url());
            }
        });

        await page.goto('./');
        await page.goto('./privacy');
        await page.goto('./user/phobos/what-is-phobos');

        expect(thirdParty).toEqual([]);
        expect(await page.context().cookies()).toEqual([]);
    });

    test('the Simple Story boxes render as admonitions', async ({ page }) => {
        await page.goto('./user/policy-reference/read');
        const simpleStory = page.locator('.theme-admonition').filter({ hasText: 'Simple Story' });
        await expect(simpleStory).toHaveCount(1);
        await expect(simpleStory).toBeVisible();
    });
});
