services:
  phobos-runner:
    build:
      context: ../../..
      dockerfile: Dockerfile
    image: ajayvir/phobos
    security_opt:
      - "seccomp:../../../security_config/seccomp_allow_bwrap.json"
      - "apparmor=docker-bwrap"
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
    command:
      - -c
      - "exec /bin/bash"
