services:
  phobos-runner:
    build:
      context: ../../..
      dockerfile: Dockerfile
    image: ajayvir/phobos
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
    command:
      - -c
      - "exec /bin/bash"
