FROM python:3.14-slim@sha256:c3e521df8b2b498a7a682e7e18676771cb80c6b75b8699af886b2d554ce40151

WORKDIR /workspace

# The build context is this directory, which holds orchestrate.py.
COPY ./orchestrate.py .

ENTRYPOINT ["python3", "orchestrate.py"]
